MG_API_KEY: "KEY"
MG_DOMAIN: "DOMAIN"
MG_SENDER: "Name <email>"
MG_RECIPIENT: "email"
MG_PUBLIC_API_KEY: "KEY"
MG_URL: "https://api.mailgun.net/v3"
SLACK_TOKEN: "TOKEN"
SLACK_CHANNEL_ID: "Right click on a channel and copy the url, the 9 characters at the end are the ID"