[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "^1.0.1"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
  version = "1.1.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"
