service: serverless-go-forms

provider:
  name: aws
  profile: default
  runtime: go1.x
  environment: ${file(./config.${self:provider.stage}.yml)}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  submit-json:
    handler: bin/function
    events:
      - http:
          path: /post
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
